services:
  _defaults:
    autowire: true
    autoconfigure: true

  Micoli\SymfonyCartography\:
    resource: '../../src/'
    exclude:
        '../../src/DependencyInjection/'
        '../../src/Model/'
        '../../src/DataStructures/'

  Micoli\SymfonyCartography\TwigExtension\ViteAssetExtension:
    arguments:
      #$isDev: '%env(VITE_DEV)%'
      $isDev: true
      $manifest: '%kernel.project_dir%/public/assets/manifest.json'
#      $cache: '@vite_pool'

  symfony-cartography-cache:
    class: Symfony\Component\Cache\Adapter\FilesystemAdapter
    arguments:
      $namespace: symfony-cartography
      $defaultLifetime: 0
      $directory: '%kernel.cache_dir%'
