twig:
    default_path: '%kernel.project_dir%/src/UserInterface/templates'
    form_themes:
        - 'form/layout.html.twig'
        - 'form/fields.html.twig'

when@test:
    twig:
        strict_variables: true
